Exercise 1, results : check almost completed

diff --git a/Exercise 1/src/results b/Exercise 1/src/results
--- a/Exercise 1/src/results
+++ b/Exercise 1/src/results
@@ -15,20 +15,20 @@
 #
 ##################################################################################################
 
-#
 TRUE="0"
 FALSE="1"
 
 # INPUT Parameters
-INPUT_FILES=""
+INPUT_FILES="" # TODO 
 OUTPUT_FILE=""
 ERRORS_FILE=""
 CHECK_FILE=""
 DEBUG="${FALSE}"
 QUIET="${FALSE}"
+CHECK="${FALSE}"
 
 
-#
+# ---------------------------------------------------------------------------------------------
 #   brief: Print in stderr and/or in external file the error messages based on user input flags
 #
 error(){
@@ -39,7 +39,7 @@ error(){
 }
 
 
-#
+# ---------------------------------------------------------------------------------------------
 #   brief: Check if input file exists and if it is valid
 #          (has correct syntax)
 #
@@ -54,30 +54,59 @@ error(){
 #           14 if file does not exist
 #
 check(){
-    if [ ${DEBUG} = "${TRUE}" ] ; then echo -e "Function: check(). Check file: ${CHECK_FILE}\t\t---Start" ; fi ;
+    if [ ${DEBUG} = "${TRUE}" ] ; then echo -e "Function: check(). Check file: ${CHECK_FILE}\t\t---START" ; fi ;
 
-    local result=0
+    local result=3
     local inputFile=$1
 
-    #File exists, is readable and is not empty
+    # File exists, is readable and is not empty BUT i don't know yet if it is acceptable
     if [ -f ${inputFile} ] && [ -r ${inputFile} ] && [ -s ${inputFile} ]; then
-        if [ ${DEBUG} = "${TRUE}" ] ; then echo -e "\t${CHECK_FILE} | File is ok!" ; fi ;
+        if [ ${DEBUG} = "${TRUE}" ] ; then echo -e "File exists, is not empty and is readable!\n" ; fi ;
+        
+        #Check if all lines of the file are in the needed format.
+        minTN=2 ; maxTN=50  # Team names must contain from minTN to maxTN letters
+        minGN=1 ; maxGN=2   # Each score must be a number with [minGN - maxGN] digits
+        lineRegex="^[[:alpha:]]{${minTN},${maxTN}}-[[:alpha:]]{${minTN},${maxTN}}:[[:digit:]]{${minGN},${maxGN}}-[[:digit:]]{${minGN},${maxGN}}$"
+        originalLines=$(cat ${inputFile})
+        goodLines=$(grep -E "${lineRegex}" ${inputFile})
 
+        if [ ${DEBUG} = "${TRUE}" ] ; then 
+            echo -e "+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
+            echo -e "~~~originalLines | (Num of lines: `echo -e "${originalLines}" | wc -l` )"
+            echo -e "${originalLines}"
+            echo -e "----------\n"
+            echo -e "~~~goodLines | (Num of lines: `echo -e "${goodLines}" | wc -l` )"
+            echo -e "${goodLines}"
+            echo -e "----------"
+            echo -e "+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++\n"
+        fi 
+        
+        #Check if all lines of the file are valid
+        if [ "${originalLines}" == "${goodLines}" ] ; then
+            if [ ${CHECK} == "${TRUE}" ] ; then echo -e "File is valid!" ; fi ; 
+            result=0
+        else
+            error "File does not have the needed format"
+            result=11
+        fi 
     elif [ ! -f ${inputFile} ] ; then
-         error "\t ${CHECK_FILE} | File does not exist"
-         result=14
+        error "File does not exist"
+        result=14
     elif [ ! -r ${inputFile} ] ; then
-         error "\t ${CHECK_FILE} | File is not readable"
-         result=13
+        error "File is not readable"
+        result=13
     elif [ ! -s ${inputFile} ] ; then
-         error "\t ${CHECK_FILE} | File is empty"  
-         result=10 
+        error "File is empty"  
+        result=10 
+    else
+        error "Unexpected error"  
     fi
 
+    if [ ${DEBUG} = "${TRUE}" ] ; then echo -e "\nFunction: check(). Check file: ${CHECK_FILE}\t\t---END" ; fi ;
     return ${result}
 }
 
-#
+# ---------------------------------------------------------------------------------------------
 #   brief: Help menu
 #
 usage() {
@@ -105,6 +134,13 @@ usage() {
     echo "   2 if unknown option,"
     echo "   3 if unexpected error,"
     echo 
+    echo "- Input file errors:"
+    echo "   10 if file is empty,"
+    echo "   11 if something is wrong with the format of the file at any point,"
+    echo "   12 if file is too big,"
+    echo "   13 if there is not read permission,"
+    echo "   14 if file does not exist"
+    echo 
     echo "Examples:"
     echo "   `basename ${0}` -e errorfile.txt inputfile.txt"
     echo "   `basename ${0}` -c inputfile.txt      # Check input's files format"
@@ -117,11 +153,13 @@ usage() {
     echo "   license         MIT License"
 }
 
-#MAIN
+
+
 #---------------------------------------------------------------------------------------------
+# MAIN
 while getopts ":c:de:ho:q" opt ; do
     case $opt in
-        c)      CHECK_FILE="${OPTARG}" ; DEBUG=${TRUE} ; check ${CHECK_FILE}  ; exit $? ;;  
+        c)      CHECK_FILE="${OPTARG}" ; CHECK="${TRUE}" ; check ${CHECK_FILE} ; exit $?;;  
         d)      DEBUG=${TRUE}                                                           ;;  
         e)      ERRORS_FILE="${OPTARG}"                                                 ;;  
         h)      usage ; exit 0                                                          ;;  
@@ -136,8 +174,8 @@ done
 shift $(( OPTIND - 1 ))
 
 if [ ${DEBUG} ] ; then
-    echo "-INPUT_FILES = ${INPUT_FILES}"
-    echo "-OUTPUT_FILE = ${OUTPUT_FILE}"
-    echo "-ERRORS_FILE = ${ERRORS_FILE}"
-    echo "-QUIET = ${QUIET}"
+    echo "-> INPUT_FILES = ${INPUT_FILES}"
+    echo "-> OUTPUT_FILE = ${OUTPUT_FILE}"
+    echo "-> ERRORS_FILE = ${ERRORS_FILE}"
+    echo "-> QUIET = ${QUIET}"
 fi
